---
- name: Deploys VM based on golden image
  hosts: 192.168.1.100 
  gather_facts: yes
  become: yes
  vars:
    pool_dir: "/home/mitre/stor"
    vcpus: 2
    ram_mb: 2048
    cleanup: yes
    net: default
    ssh_pub_key: "/home/mitre/.ssh/id_rsa.pub"

  tasks:
    - name: KVM Provision role
      loop:
        - tst1      
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ item }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"

    