---
- hosts: all
  collections:
    - community.libvirt.virt
- name: Deploys VM based on golden image
  hosts: localhost
  gather_facts: yes
  become: yes
  vars:
    pool_dir: "/var/lib/libvirt/images/pool"
    vcpus: 2
    ram_mb: 2048
    cleanup: yes
    net: default
    ssh_pub_key: "/home/mitre/.ssh/id_rsa.pub"

  tasks:
    - name: KVM Provision role
      loop:
        - tst1
        - tst2
        - tst3
        - tst4
        - tst5      
      include_role:
        name: kvm_provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ item }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"
        vm_net: "{{ net }}"
        cleanup_tmp: "{{ cleanup }}"
        ssh_key: "{{ ssh_pub_key }}"

    